import { ApiPerson } from '@app-types';

export const ApiPeopleMockList: ApiPerson[] = [
  {
    url: 'https://swapi.dev/api/people/1/',
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/2/',
    name: 'C-3PO',
    height: '167',
    mass: '75',
    hair_color: 'n/a',
    skin_color: 'gold',
    eye_color: 'yellow',
    birth_year: '112BBY',
    gender: 'n/a',
  },
  {
    url: 'https://swapi.dev/api/people/3/',
    name: 'R2-D2',
    height: '96',
    mass: '32',
    hair_color: 'n/a',
    skin_color: 'white, blue',
    eye_color: 'red',
    birth_year: '33BBY',
    gender: 'n/a',
  },
  {
    url: 'https://swapi.dev/api/people/4/',
    name: 'Darth Vader',
    height: '202',
    mass: '136',
    hair_color: 'none',
    skin_color: 'white',
    eye_color: 'yellow',
    birth_year: '41.9BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/5/',
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '19BBY',
    gender: 'female',
  },
  {
    url: 'https://swapi.dev/api/people/6/',
    name: 'Owen Lars',
    height: '178',
    mass: '120',
    hair_color: 'brown, grey',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '52BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/7/',
    name: 'Beru Whitesun lars',
    height: '165',
    mass: '75',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '47BBY',
    gender: 'female',
  },
  {
    url: 'https://swapi.dev/api/people/8/',
    name: 'R5-D4',
    height: '97',
    mass: '32',
    hair_color: 'n/a',
    skin_color: 'white, red',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'n/a',
  },
  {
    url: 'https://swapi.dev/api/people/9/',
    name: 'Biggs Darklighter',
    height: '183',
    mass: '84',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '24BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/10/',
    name: 'Obi-Wan Kenobi',
    height: '182',
    mass: '77',
    hair_color: 'auburn, white',
    skin_color: 'fair',
    eye_color: 'blue-gray',
    birth_year: '57BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/11/',
    name: 'Anakin Skywalker',
    height: '188',
    mass: '84',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '41.9BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/12/',
    name: 'Wilhuff Tarkin',
    height: '180',
    mass: 'unknown',
    hair_color: 'auburn, grey',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '64BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/13/',
    name: 'Chewbacca',
    height: '228',
    mass: '112',
    hair_color: 'brown',
    skin_color: 'unknown',
    eye_color: 'blue',
    birth_year: '200BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/14/',
    name: 'Han Solo',
    height: '180',
    mass: '80',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '29BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/15/',
    name: 'Greedo',
    height: '173',
    mass: '74',
    hair_color: 'n/a',
    skin_color: 'green',
    eye_color: 'black',
    birth_year: '44BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/16/',
    name: 'Jabba Desilijic Tiure',
    height: '175',
    mass: '1,358',
    hair_color: 'n/a',
    skin_color: 'green-tan, brown',
    eye_color: 'orange',
    birth_year: '600BBY',
    gender: 'hermaphrodite',
  },
  {
    url: 'https://swapi.dev/api/people/17/',
    name: 'Wedge Antilles',
    height: '170',
    mass: '77',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'hazel',
    birth_year: '21BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/18/',
    name: 'Jek Tono Porkins',
    height: '180',
    mass: '110',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/19/',
    name: 'Yoda',
    height: '66',
    mass: '17',
    hair_color: 'white',
    skin_color: 'green',
    eye_color: 'brown',
    birth_year: '896BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/20/',
    name: 'Palpatine',
    height: '170',
    mass: '75',
    hair_color: 'grey',
    skin_color: 'pale',
    eye_color: 'yellow',
    birth_year: '82BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/21/',
    name: 'Boba Fett',
    height: '183',
    mass: '78.2',
    hair_color: 'black',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '31.5BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/22/',
    name: 'IG-88',
    height: '200',
    mass: '140',
    hair_color: 'none',
    skin_color: 'metal',
    eye_color: 'red',
    birth_year: '15BBY',
    gender: 'none',
  },
  {
    url: 'https://swapi.dev/api/people/23/',
    name: 'Bossk',
    height: '190',
    mass: '113',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'red',
    birth_year: '53BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/24/',
    name: 'Lando Calrissian',
    height: '177',
    mass: '79',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '31BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/25/',
    name: 'Lobot',
    height: '175',
    mass: '79',
    hair_color: 'none',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '37BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/26/',
    name: 'Ackbar',
    height: '180',
    mass: '83',
    hair_color: 'none',
    skin_color: 'brown mottle',
    eye_color: 'orange',
    birth_year: '41BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/27/',
    name: 'Mon Mothma',
    height: '150',
    mass: 'unknown',
    hair_color: 'auburn',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '48BBY',
    gender: 'female',
  },
  {
    url: 'https://swapi.dev/api/people/28/',
    name: 'Arvel Crynyd',
    height: 'unknown',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/29/',
    name: 'Wicket Systri Warrick',
    height: '88',
    mass: '20',
    hair_color: 'brown',
    skin_color: 'brown',
    eye_color: 'brown',
    birth_year: '8BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/30/',
    name: 'Nien Nunb',
    height: '160',
    mass: '68',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/31/',
    name: 'Qui-Gon Jinn',
    height: '193',
    mass: '89',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '92BBY',
    gender: 'male',
  },
  {
    url: 'https://swapi.dev/api/people/32/',
    name: 'Nute Gunray',
    height: '191',
    mass: '90',
    hair_color: 'none',
    skin_color: 'mottled green',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'male',
  },
];
