import { Person } from '@app-types/person';

export const PeopleMockList: Person[] = [
  {
    id: '1',
    url: 'https://swapi.dev/api/people/1/',
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hairColor: 'blond',
    skinColor: 'fair',
    eyeColor: 'blue',
    birthYear: '19BBY',
    gender: 'male',
  },
  {
    id: '2',
    url: 'https://swapi.dev/api/people/2/',
    name: 'C-3PO',
    height: '167',
    mass: '75',
    hairColor: 'n/a',
    skinColor: 'gold',
    eyeColor: 'yellow',
    birthYear: '112BBY',
    gender: 'n/a',
  },
  {
    id: '3',
    url: 'https://swapi.dev/api/people/3/',
    name: 'R2-D2',
    height: '96',
    mass: '32',
    hairColor: 'n/a',
    skinColor: 'white, blue',
    eyeColor: 'red',
    birthYear: '33BBY',
    gender: 'n/a',
  },
  {
    id: '4',
    url: 'https://swapi.dev/api/people/4/',
    name: 'Darth Vader',
    height: '202',
    mass: '136',
    hairColor: 'none',
    skinColor: 'white',
    eyeColor: 'yellow',
    birthYear: '41.9BBY',
    gender: 'male',
  },
  {
    id: '5',
    url: 'https://swapi.dev/api/people/5/',
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hairColor: 'brown',
    skinColor: 'light',
    eyeColor: 'brown',
    birthYear: '19BBY',
    gender: 'female',
  },
  {
    id: '6',
    url: 'https://swapi.dev/api/people/6/',
    name: 'Owen Lars',
    height: '178',
    mass: '120',
    hairColor: 'brown, grey',
    skinColor: 'light',
    eyeColor: 'blue',
    birthYear: '52BBY',
    gender: 'male',
  },
  {
    id: '7',
    url: 'https://swapi.dev/api/people/7/',
    name: 'Beru Whitesun lars',
    height: '165',
    mass: '75',
    hairColor: 'brown',
    skinColor: 'light',
    eyeColor: 'blue',
    birthYear: '47BBY',
    gender: 'female',
  },
  {
    id: '8',
    url: 'https://swapi.dev/api/people/8/',
    name: 'R5-D4',
    height: '97',
    mass: '32',
    hairColor: 'n/a',
    skinColor: 'white, red',
    eyeColor: 'red',
    birthYear: 'unknown',
    gender: 'n/a',
  },
  {
    id: '9',
    url: 'https://swapi.dev/api/people/9/',
    name: 'Biggs Darklighter',
    height: '183',
    mass: '84',
    hairColor: 'black',
    skinColor: 'light',
    eyeColor: 'brown',
    birthYear: '24BBY',
    gender: 'male',
  },
  {
    id: '10',
    url: 'https://swapi.dev/api/people/10/',
    name: 'Obi-Wan Kenobi',
    height: '182',
    mass: '77',
    hairColor: 'auburn, white',
    skinColor: 'fair',
    eyeColor: 'blue-gray',
    birthYear: '57BBY',
    gender: 'male',
  },
  {
    id: '11',
    url: 'https://swapi.dev/api/people/11/',
    name: 'Anakin Skywalker',
    height: '188',
    mass: '84',
    hairColor: 'blond',
    skinColor: 'fair',
    eyeColor: 'blue',
    birthYear: '41.9BBY',
    gender: 'male',
  },
  {
    id: '12',
    url: 'https://swapi.dev/api/people/12/',
    name: 'Wilhuff Tarkin',
    height: '180',
    mass: 'unknown',
    hairColor: 'auburn, grey',
    skinColor: 'fair',
    eyeColor: 'blue',
    birthYear: '64BBY',
    gender: 'male',
  },
  {
    id: '13',
    url: 'https://swapi.dev/api/people/13/',
    name: 'Chewbacca',
    height: '228',
    mass: '112',
    hairColor: 'brown',
    skinColor: 'unknown',
    eyeColor: 'blue',
    birthYear: '200BBY',
    gender: 'male',
  },
  {
    id: '14',
    url: 'https://swapi.dev/api/people/14/',
    name: 'Han Solo',
    height: '180',
    mass: '80',
    hairColor: 'brown',
    skinColor: 'fair',
    eyeColor: 'brown',
    birthYear: '29BBY',
    gender: 'male',
  },
  {
    id: '15',
    url: 'https://swapi.dev/api/people/15/',
    name: 'Greedo',
    height: '173',
    mass: '74',
    hairColor: 'n/a',
    skinColor: 'green',
    eyeColor: 'black',
    birthYear: '44BBY',
    gender: 'male',
  },
  {
    id: '16',
    url: 'https://swapi.dev/api/people/16/',
    name: 'Jabba Desilijic Tiure',
    height: '175',
    mass: '1,358',
    hairColor: 'n/a',
    skinColor: 'green-tan, brown',
    eyeColor: 'orange',
    birthYear: '600BBY',
    gender: 'hermaphrodite',
  },
  {
    id: '17',
    url: 'https://swapi.dev/api/people/17/',
    name: 'Wedge Antilles',
    height: '170',
    mass: '77',
    hairColor: 'brown',
    skinColor: 'fair',
    eyeColor: 'hazel',
    birthYear: '21BBY',
    gender: 'male',
  },
  {
    id: '18',
    url: 'https://swapi.dev/api/people/18/',
    name: 'Jek Tono Porkins',
    height: '180',
    mass: '110',
    hairColor: 'brown',
    skinColor: 'fair',
    eyeColor: 'blue',
    birthYear: 'unknown',
    gender: 'male',
  },
  {
    id: '19',
    url: 'https://swapi.dev/api/people/19/',
    name: 'Yoda',
    height: '66',
    mass: '17',
    hairColor: 'white',
    skinColor: 'green',
    eyeColor: 'brown',
    birthYear: '896BBY',
    gender: 'male',
  },
  {
    id: '20',
    url: 'https://swapi.dev/api/people/20/',
    name: 'Palpatine',
    height: '170',
    mass: '75',
    hairColor: 'grey',
    skinColor: 'pale',
    eyeColor: 'yellow',
    birthYear: '82BBY',
    gender: 'male',
  },
  {
    id: '21',
    url: 'https://swapi.dev/api/people/21/',
    name: 'Boba Fett',
    height: '183',
    mass: '78.2',
    hairColor: 'black',
    skinColor: 'fair',
    eyeColor: 'brown',
    birthYear: '31.5BBY',
    gender: 'male',
  },
  {
    id: '22',
    url: 'https://swapi.dev/api/people/22/',
    name: 'IG-88',
    height: '200',
    mass: '140',
    hairColor: 'none',
    skinColor: 'metal',
    eyeColor: 'red',
    birthYear: '15BBY',
    gender: 'none',
  },
  {
    id: '23',
    url: 'https://swapi.dev/api/people/23/',
    name: 'Bossk',
    height: '190',
    mass: '113',
    hairColor: 'none',
    skinColor: 'green',
    eyeColor: 'red',
    birthYear: '53BBY',
    gender: 'male',
  },
  {
    id: '24',
    url: 'https://swapi.dev/api/people/24/',
    name: 'Lando Calrissian',
    height: '177',
    mass: '79',
    hairColor: 'black',
    skinColor: 'dark',
    eyeColor: 'brown',
    birthYear: '31BBY',
    gender: 'male',
  },
  {
    id: '25',
    url: 'https://swapi.dev/api/people/25/',
    name: 'Lobot',
    height: '175',
    mass: '79',
    hairColor: 'none',
    skinColor: 'light',
    eyeColor: 'blue',
    birthYear: '37BBY',
    gender: 'male',
  },
  {
    id: '26',
    url: 'https://swapi.dev/api/people/26/',
    name: 'Ackbar',
    height: '180',
    mass: '83',
    hairColor: 'none',
    skinColor: 'brown mottle',
    eyeColor: 'orange',
    birthYear: '41BBY',
    gender: 'male',
  },
  {
    id: '27',
    url: 'https://swapi.dev/api/people/27/',
    name: 'Mon Mothma',
    height: '150',
    mass: 'unknown',
    hairColor: 'auburn',
    skinColor: 'fair',
    eyeColor: 'blue',
    birthYear: '48BBY',
    gender: 'female',
  },
  {
    id: '28',
    url: 'https://swapi.dev/api/people/28/',
    name: 'Arvel Crynyd',
    height: 'unknown',
    mass: 'unknown',
    hairColor: 'brown',
    skinColor: 'fair',
    eyeColor: 'brown',
    birthYear: 'unknown',
    gender: 'male',
  },
  {
    id: '29',
    url: 'https://swapi.dev/api/people/29/',
    name: 'Wicket Systri Warrick',
    height: '88',
    mass: '20',
    hairColor: 'brown',
    skinColor: 'brown',
    eyeColor: 'brown',
    birthYear: '8BBY',
    gender: 'male',
  },
  {
    id: '30',
    url: 'https://swapi.dev/api/people/30/',
    name: 'Nien Nunb',
    height: '160',
    mass: '68',
    hairColor: 'none',
    skinColor: 'grey',
    eyeColor: 'black',
    birthYear: 'unknown',
    gender: 'male',
  },
  {
    id: '31',
    url: 'https://swapi.dev/api/people/31/',
    name: 'Qui-Gon Jinn',
    height: '193',
    mass: '89',
    hairColor: 'brown',
    skinColor: 'fair',
    eyeColor: 'blue',
    birthYear: '92BBY',
    gender: 'male',
  },
  {
    id: '32',
    url: 'https://swapi.dev/api/people/32/',
    name: 'Nute Gunray',
    height: '191',
    mass: '90',
    hairColor: 'none',
    skinColor: 'mottled green',
    eyeColor: 'red',
    birthYear: 'unknown',
    gender: 'male',
  },
];
